name: flutter_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  google_fonts: ^6.2.1
  http: ^1.2.1
  provider: ^6.1.2
  intl: ^0.18.1
  url_launcher: ^6.1.7 
  unicons: ^2.0.0
  font_awesome_flutter: ^10.1.0
  table_calendar: ^3.0.0
  


  flutter_svg: any
  mysql1: ^0.20.0
  image_picker: ^1.1.2
  cloud_firestore: ^5.4.5
  dotted_border: ^2.1.0
  file_picker: ^8.1.4
  get: ^4.7.2
  pie_chart: ^5.4.0
  fl_chart: ^0.71.0
  shared_preferences: ^2.5.3
  sqflite_common_ffi: ^2.3.5
  sqflite_common_ffi_web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - assets/vectors/
    - assets/career_coaching/
    
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
